### PR TITLE
Further style and props handling in Dashboard

### PR DESCRIPTION
**Pull request by sk-saha**

### CODE REVIEW

**Review by michigg — COMMENTED** [review]
Can we write some unit tests for that?

**Comment by sk-saha** [comment]
> Can we write some unit tests for that?

For the watchers?

**Comment by michigg** [comment]
> > Can we write some unit tests for that?
> 
> For the watchers?

For the component. But you can only test the watcher part

**Review by michigg — APPROVED** [review]
Like it 👍

**Pull request merged**
